baseURL = 'https://richardfagundes.com'
languageCode = 'pt-BR'
title = 'Richard Fagundes'
summaryLength = 20

[params]
title = "Richard Fagundes"
description = "Arquitetando, desenvolvendo e escalando soluções robustas"
location = ["São Paulo, Brazil"]
copyright = "© 2024 Richard Fagundes All Rights Reserved"

[[params.contact]]
name = "LinkedIn"
text = "linkedin.com/in/richardnfag"
url = "https://linkedin.com/in/richardnfag"

[[params.contact]]
name = "Calendly"
text = "https://calendly.com/richardfagundes"
url = "https://calendly.com/richardfagundes"

[[params.contact]]
name = "E-mail"
text = "contato@richardfagundes.com"
url = "mailto:contato@richardfagundes.com"

[[params.contact]]
name = "Telefone / WhatsApp"
text = "+55 (14) 99645-9969"
url = "https://api.whatsapp.com/send?phone=5514996459969"

[menus]
main = [
    { name = "Home", url = "/#hero", weight = 1 },
    { name = "Serviços", url = "/#portfolio", weight = 2 },
    { name = "Sobre mim", url = "/#about", weight = 4 },
]
footer = [
    { name = "Home", url = "/#hero", weight = 1 },
    { name = "How we work", url = "/#", weight = 2 },
    { name = "Our team", url = "/#", weight = 3 },
    { name = "Pricing", url = "/#", weight = 4 },
    { name = "Blog", url = "/blog", weight = 5 },
]

[[menus.buttons]]
name = "Agendar uma reunião"
url = "https://calendly.com/richardfagundes"
weight = 5
pre = "btn btn-primary text-light"

[taxonomies]
series = "series"
tags = "tags"

[markup.highlight]
codeFences = true
noClasses = true
style = "xcode-dark"
tabWidth = 4
